export const defaultMails = [
    {
        id: '49Fsm3',
        createdAt: 1714077332272,
        subject: 'Meeting Reminder',
        body: 'Thank you for your recent inquiry about Your Order Has Shipped. I have attached more details in this email for your review.',
        isRead: false,
        sentAt: 1714077560443,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'support@company.com',
        to: 'user@gmail.com'
    },
    {
        id: '19fhns',
        createdAt: 1714078831270,
        subject: 'Let\'s Gather Again This Thanksgiving!',
        body: `Hi, Suzan & Friends!,
        
I hope this email finds you well. As the fall leaves start to turn their beautiful shades of red, orange, and yellow, it's hard not to feel the warmth of the season settling in. And you know what that means—Thanksgiving is right around the corner!
            
It feels like ages since we’ve all been under the same roof, laughing over old stories and new ones alike. So, I’m excited to share that this year, we’re hosting Thanksgiving at our place, and you’re absolutely invited! We’ll be doing it potluck-style, as always, and I’m already looking forward to all the delicious dishes I know you’ll bring. Your [famous dish] is always a hit, and I know everyone will be thrilled to see it on the table again.
            
This year, I’ve been reflecting a lot on how much family and friends mean to me. The past few years have been challenging in so many ways, but if anything, they’ve made me realize just how important it is to make time for the people who matter most. I don’t want another year to pass without taking a moment to gather, relax, and enjoy each other’s company. After all, it's those simple moments that make the best memories, don't you think?
            
We'll have the big dinner around 4 PM, but feel free to come earlier if you'd like to help with prep or just hang out. I’ve also been thinking about adding a new twist this year—how do you feel about some friendly competition with a family trivia game after dinner? Nothing too intense, just something fun to keep the energy up while we digest all that turkey!
            
I’d love to know if you’ll be able to make it. It would mean the world to have you there. Plus, if you need a ride, let me know. I’m sure we can arrange something—anything to make sure you can join the fun.
            
Can’t wait to hear back from you and, hopefully, see you in person for a warm and cozy Thanksgiving!
            
With love and gratitude,
Christopher`,
        isRead: false,
        sentAt: 1714078831103,
        isPrimary: false,
        isPromotions: false,
        isSocial: true,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'Chris@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'inx66s',
        createdAt: 1714078801270,
        subject: 'Pot Luck',
        body: `Hi Dad,

I hope this email finds you well! I wanted to reach out and discuss the upcoming potluck we’ve been planning for next weekend. I’m really looking forward to it and think it could be a great opportunity for everyone to come together and enjoy some good food and company.

As we start to finalize the details, I thought it would be helpful to coordinate who’s bringing what. I plan to make my famous chili, which I think everyone will love. It’s always a hit at gatherings! If you’re interested, you could bring your delicious cornbread to go along with it. I remember how much everyone enjoyed that last time. 

Also, we should think about drinks and any other side dishes. Maybe we can ask the family if anyone wants to bring a salad or dessert? I can send out a quick message to the group and see what everyone wants to contribute. It’ll be nice to have a variety of dishes to enjoy. 

Let me know what you think about the cornbread idea and if you have any other dishes in mind. I want to make sure we have plenty of food to share and enjoy. 

Looking forward to catching up with everyone and having a great time at the potluck. If you have any other ideas or suggestions for the event, feel free to share! 

Take care, and I’ll talk to you soon!

Best,
John Snow`,
        isRead: false,
        sentAt: 1714078811103,
        isPrimary: false,
        isPromotions: false,
        isSocial: true,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'John.S@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'TK91tS',
        createdAt: 1721217376719,
        subject: 'Catch Up Soon',
        body: 'Thank you for your recent inquiry about Weekly Newsletter. I have attached more details in this email for your review.',
        isRead: false,
        sentAt: 1721217608719,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'newsletter@yahoo.com',
        to: 'user@gmail.com'
    },
    {
        id: 'i38MT0',
        createdAt: 1712616710784,
        subject: 'Exclusive Invitation',
        body: 'We are excited to share that Weekly Newsletter has been improved significantly. Find out more in this email.',
        isRead: false,
        sentAt: 1712617494105,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'service@gmail.com',
        to: 'user@gmail.com'
    },
    {
        id: '3jF5Mp',
        createdAt: 1725344847281,
        subject: 'Your Account Info',
        body: 'This email contains important information regarding Your Account Info. Make sure to read through it carefully.',
        isRead: true,
        sentAt: 1725345135357,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'newsletter@gmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'v82g1l',
        createdAt: 1720915046071,
        subject: 'Let’s Connect',
        body: 'Hi, just a quick note regarding Exclusive Invitation. I wanted to check in and discuss a few points further. Let me know when you’re free.',
        isRead: false,
        sentAt: 1720915120190,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'info@gmail.com',
        to: 'user@gmail.com'
    },
    {
        id: '1y47NX',
        createdAt: 1727469117963,
        subject: 'Invoice Attached',
        body: 'Hi, just a quick note regarding Important Update. I wanted to check in and discuss a few points further. Let me know when you’re free.',
        isRead: true,
        sentAt: 1727469798483,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'admin@gov.us',
        to: 'user@gmail.com'
    },
    {
        id: 'Cgm3r',
        createdAt: 1716431421568,
        subject: 'Invoice Attached',
        body: 'Thanks for connecting! I hope everything about Important Update is clear now. Feel free to reach out for more information.',
        isRead: false,
        sentAt: 1716431785415,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'sales@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'lq9T8s',
        createdAt: 1719187215812,
        subject: 'Weekly Newsletter',
        body: 'We are excited to share that Exclusive Invitation has been improved significantly. Find out more in this email.',
        isRead: true,
        sentAt: 1719187867195,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'contact@company.com',
        to: 'user@gmail.com'
    },
    {
        id: '1b0Apk',
        createdAt: 1714528256416,
        subject: 'Discount Offer!',
        body: 'Thank you for your recent inquiry about Discount Offer! I have attached more details in this email for your review.',
        isRead: true,
        sentAt: 1714528367372,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'service@yahoo.com',
        to: 'user@gmail.com'
    },
    {
        id: 'P4v4Kw',
        createdAt: 1722364510542,
        subject: 'Important Update',
        body: 'Please be informed about the upcoming changes related to Important Update. Stay tuned for more updates.',
        isRead: false,
        sentAt: 1722365156733,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'support@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'S9lNP2',
        createdAt: 1718065157216,
        subject: 'Let’s Connect',
        body: 'Thanks for connecting! I hope everything about Your Account Info is clear now. Feel free to reach out for more information.',
        isRead: false,
        sentAt: 1718065903321,
        isPrimary: false,
        isPromotions: false,
        isSocial: true,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'newsletter@gmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'Oi7J19',
        createdAt: 1719365512043,
        subject: 'Schedule a Call',
        body: 'This email contains important information regarding Let’s Connect. Make sure to read through it carefully.',
        isRead: false,
        sentAt: 1719365900498,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'contact@gmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'jHYm91',
        createdAt: 1715235703147,
        subject: 'New Features Available',
        body: 'Thanks for connecting! I hope everything about New Features Available is clear now. Feel free to reach out for more information.',
        isRead: false,
        sentAt: 1715235906612,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'support@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'cgL8hF',
        createdAt: 1718677936354,
        subject: 'Important Update',
        body: 'Thanks for connecting! I hope everything about Important Update is clear now. Feel free to reach out for more information.',
        isRead: false,
        sentAt: 1718678747583,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'info@company.com',
        to: 'user@gmail.com'
    },
    {
        id: '1R4F7d',
        createdAt: 1607065268011,
        subject: 'Thank You for Your Purchase',
        body: 'Please review the latest information related to New Features Available. Looking forward to your feedback soon.',
        isRead: true,
        sentAt: 1607065628482,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'newsletter@company.com',
        to: 'user@gmail.com'
    },
    {
        id: '2mtF3D',
        createdAt: 1715127535749,
        subject: 'Catch Up Soon',
        body: 'I noticed that you have some concerns about Important Update. Would love to connect and offer some help where I can.',
        isRead: false,
        sentAt: 1715127830191,
        isPrimary: false,
        isPromotions: false,
        isSocial: true,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'admin@company.com',
        to: 'user@gmail.com'
    },
    {
        id: 'MNx7bC',
        createdAt: 1718592335731,
        subject: 'Your Order Has Shipped',
        body: 'Your recent interest in Catch Up Soon has caught our attention. Here’s what we can offer you as a next step.',
        isRead: false,
        sentAt: 1718592886368,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'service@yahoo.com',
        to: 'user@gmail.com'
    },
    {
        id: 'Yo92at',
        createdAt: 1717466542305,
        subject: 'Survey Request',
        body: 'Please be informed about the upcoming changes related to Catch Up Soon. Stay tuned for more updates.',
        isRead: false,
        sentAt: 1717467026678,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'admin@gov.us',
        to: 'user@gmail.com'
    },
    {
        id: 'r3Me56',
        createdAt: 1719401306463,
        subject: 'Weekly Newsletter',
        body: 'This email contains important information regarding Discount Offer!. Make sure to read through it carefully.',
        isRead: true,
        sentAt: 1719401649037,
        isPrimary: false,
        isPromotions: true,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'support@hotmail.com',
        to: 'user@gmail.com'
    },
    {
        id: 'zFk1Jp',
        createdAt: 1719758974163,
        subject: 'Important Update',
        body: 'Your recent interest in Catch Up Soon has caught our attention. Here’s what we can offer you as a next step.',
        isRead: false,
        sentAt: 1719759232918,
        isPrimary: true,
        isPromotions: false,
        isSocial: false,
        isStarred: false,
        isArchived: false,
        removedAt: null,
        from: 'service@company.com',
        to: 'user@gmail.com'
    }
]
